#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-bumpversion
Version  : 0.6.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/34/f5/e95fcd8de146884cf5ecf30f227e13c3615584ccef8c8cca18140a27b664/bumpversion-0.6.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/34/f5/e95fcd8de146884cf5ecf30f227e13c3615584ccef8c8cca18140a27b664/bumpversion-0.6.0.tar.gz
Summary  : Version-bump your software with a single command!
Group    : Development/Tools
License  : MIT
Requires: pypi-bumpversion-license = %{version}-%{release}
Requires: pypi-bumpversion-python = %{version}-%{release}
Requires: pypi-bumpversion-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(bump2version)

%description
**⚠️ Current status of this project**
* 🎬If you want to start **using bumpversion**, you're best advised to **install one of the maintained forks**, e.g. ➡ `@c4urself's bump2version <https://github.com/c4urself/bump2version/#installation>`_.
* 🔨If you want to **help maintain** bumpversion, there's an `ongoing discussion about merging the fork back to the original project as well as forming a group of maintainers <https://github.com/c4urself/bump2version/issues/86>`_ to ensure a long-term future for this project. Please contribute.

%package license
Summary: license components for the pypi-bumpversion package.
Group: Default

%description license
license components for the pypi-bumpversion package.


%package python
Summary: python components for the pypi-bumpversion package.
Group: Default
Requires: pypi-bumpversion-python3 = %{version}-%{release}

%description python
python components for the pypi-bumpversion package.


%package python3
Summary: python3 components for the pypi-bumpversion package.
Group: Default
Requires: python3-core
Provides: pypi(bumpversion)
Requires: pypi(bump2version)

%description python3
python3 components for the pypi-bumpversion package.


%prep
%setup -q -n bumpversion-0.6.0
cd %{_builddir}/bumpversion-0.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641550379
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-bumpversion
cp %{_builddir}/bumpversion-0.6.0/LICENSE.rst %{buildroot}/usr/share/package-licenses/pypi-bumpversion/e12aef25fc32114a2b056953d9d0cba9a306369c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-bumpversion/e12aef25fc32114a2b056953d9d0cba9a306369c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
